### ISSUE TITLE
Unity2017.2.1f1 error

### ISSUE THREAD

**Issue by DashaTseng** [noir-neo/UnityARKitMultipeerConnectivity#17]
I found this error when I unzip the project. my unity is 2017.2.1f1 Assets/Plugins/UniRx/Scripts/UnityEngineBridge/UnityEqualityComparer.cs(7,25): error CS0101: The namespace `UniRx' already contains a definition for `UnityEqualityComparer'

**Comment by noir-neo** [comment]
Thank you for reporting 👍 
I found it the example codes are dependent on Unity 2018.2 or newer 🙇 
this is because it using dotnet 4.x and incremental compiler.

You now have 2 options.
1. If you want to use example project, you have to upgrade your Unity
1. If you need only native interfaces, you can remove directories: `Plugins/UniRx`, `Resources`, `Scenes`, `UnityARKitPluginExtensions`, `UnityMultipeerConnectivity/Scripts`

I'll organize dependencies and close this issue 😎
